### ISSUE TITLE
show it in file diff

### ISSUE THREAD

**Issue by windrg** [gregsexton/gitv#101]
Hi Greg,

Thanks for your this great work first of all.
BTW,
I'd like to know how to open like you at 

- gitv in file mode, performing a file diff [http://www.gregsexton.org/images/gitv/gitv-file-diff.jpg]
- gitv in browser mode, diffing a file [http://www.gregsexton.org/images/gitv/gitv-diff.jpg]

And  it would be appreciated for you to share how to make it default.

Thanks.

**Comment by roxma** [comment]
The docs says I should use `:Gitv!`, but it does not work like that for me

**Comment by AlterDepp** [comment]
Hi Roxama, `:Gitv!` should open the history for the file in the buffer, if it is controlled by git. What is the output for you?
Stefan

**Comment by roxma** [comment]
@AlterDepp 

Oh It does open the history file for me. 

I just figure how to show the splited diff windows.

Just Select the commit and press 'D' to open it.
