### ISSUE TITLE
Possibility to customize mappings

### ISSUE THREAD

**Issue by sassanh** [gregsexton/gitv#103]
Is it possible to customize mappings in `gitv` buffers?

**Comment by AlterDepp** [comment]
I think you can't, but the mappings are local to the Gitv-buffer.

**Comment by sassanh** [comment]
The problem is I have `nnoremap <c-j> <c-w>j` for example but gitv overrides it.

**Comment by rbong** [comment]
There is an option to use the variable `g:Gitv_DoNotMapCtrlKey`.

However, I've added the ability to overwrite any of the default mappings. Please see `:help gitv-custom-browser-mappings`. `g:Gitv_DoNotMapCtrlKey` is still respected.

**Comment by sassanh** [comment]
thanks
