### ISSUE TITLE
Possibility of creating git gui?

### ISSUE THREAD

**Issue by pyros2097** [gregsexton/gitv#107]
Generally in my usual workflow I use gitk to see all commits and git gui to commit files. Is is possible to have git gui along with gitv or would another plugin suffice? Also how would I go about in developing such a plugin which is going to have atleast 4 windows showing all the details and will allow me to stage and commit also.

**Comment by rbong** [comment]
As far as I know, you can perform all branch management with gitv and all file management with fugitive. While in gitv, you can still use `:Gstatus` to stage files and `:Gcommit` to perform commits. What other aspects of the GUIs you use are missing?

**Comment by pyros2097** [comment]
Whoaa!! you @rbong 
![rbong](https://avatars0.githubusercontent.com/u/5875706?v=3&s=400)
and @alexcrichton
![alex](https://avatars2.githubusercontent.com/u/64996?v=3&s=140)

look the same. Almost got confused. Haha.

Anyways on the gui side. I was thinking of some interface where I can move files up and down from an staged window and an unstaged window and a preview window on the currently selected file.

|---------------------------------------------------|
|    Staged      |      Selected File                           |
|   1                |                                                     | 
|   2                |                                                     |
|                     |                                                     |
| -------------|                                                      |
|   Unstaged   |                                                     |
|   1                |                                                     |
|   2                |---------------------------------- |
|                     | Commit Message                        |
|--------------------------------------------------|

Oh wait just saw https://github.com/tpope/vim-fugitive. Yeah it does it functionally like this. But it will look a lot like git gui and easier and better with this layout.

**Comment by rbong** [comment]
I wonder if Alex is wondering why he's getting notifications.

This would really go against gitv's design as a fugitive plugin and branch viewer, as we would need to create our own, separate interface for staging files.

I would even recommend that this could be its own plugin.

Unfortunately, I'm going to have to close this topic, because I just don't think it's right for gitv. Thank you for your suggestions.
