### ISSUE TITLE
Maps not responding - Vim 8.0 compatible?

### ISSUE THREAD

**Issue by MattSPalmer** [gregsexton/gitv#111]
Hi there,

I've tried clearing out my vimrc until nothing but fugitive and gitv are left, and I still am not having success using any of the maps in browser or file mode; there's no error message, and when I look at the result of `nmap`, everything is where it should be. I'm using junegunn's [vim-plug](https://github.com/junegunn/vim-plug) to load plugins.

Is gitv not supported in vim 8.x?

**Comment by rbong** [comment]
Hi, gitv should work in vim8.x
Sorry for your troubles.
I have installed on vim 8.0.0086-1-x86_64 and 8.0.0149-1-x86_64 with a .vimrc that looks like this
```
call plug#begin('~/.vim/plugged')
    Plug 'tpope/vim-fugitive'
    Plug 'gregsexton/gitv'
call plug#end()
```
And a fresh `PlugInstall`.
I am not encountering this error. 
Could you please post the output of `:version` and any differences you have in your .vimrc?

**Comment by rbong** [comment]
Also, I would try getting the latest gitv if you don't already have it.

**Comment by MattSPalmer** [comment]
Thanks for your attention to this - I was unable to reproduce the issue with a similar vimrc on a different machine. Once I have access to the other machine again I'll follow the recommended steps.

**Comment by MattSPalmer** [comment]
Issue reproduced on my work machine, a mid-2014 MBP on El Cap. For example, having invoked `:Gitv!` in a file buffer, I'll hit `D` to see a diff and nothing happens.

For .vimrc  I used the exact text you provided.

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 13 2017 15:31:30)
MacOS X (unix) version
Included patches: 1-176
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +cscope          -footer          +menu            +num64           +startuptime     +virtualedit
+arabic          +cursorbind      +fork()          +mksession       +packages        +statusline      +visual
+autocmd         +cursorshape     -gettext         +modify_fname    +path_extra      -sun_workshop    +visualextra
-balloon_eval    +dialog_con      -hangul_input    +mouse           +perl            +syntax          +viminfo
-browse          +diff            +iconv           -mouseshape      +persistent_undo +tag_binary      +vreplace
++builtin_terms  +digraphs        +insert_expand   +mouse_dec       +postscript      +tag_old_static  +wildignore
+byte_offset     -dnd             +job             -mouse_gpm       +printer         -tag_any_white   +wildmenu
+channel         -ebcdic          +jumplist        -mouse_jsbterm   +profile         -tcl             +windows
+cindent         +emacs_tags      +keymap          +mouse_netterm   -python          +termguicolors   +writebackup
-clientserver    +eval            +lambda          +mouse_sgr       +python3         +terminfo        -X11
+clipboard       +ex_extra        +langmap         -mouse_sysmouse  +quickfix        +termresponse    -xfontset
+cmdline_compl   +extra_search    +libcall         +mouse_urxvt     +reltime         +textobjects     -xim
+cmdline_hist    +farsi           +linebreak       +mouse_xterm     +rightleft       +timers          -xpm
+cmdline_info    +file_in_path    +lispindent      +multi_byte      +ruby            +title           -xsmp
+comments        +find_in_path    +listcmds        +multi_lang      +scrollbind      -toolbar         -xterm_clipboard
+conceal         +float           +localmap        -mzscheme        +signs           +user_commands   -xterm_save
+cryptv          +folding         +lua             +netbeans_intg   +smartindent     +vertsplit
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation:
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/u
sr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -
mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.
0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python3/Frameworks/Python.framework/Versions
/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.4.0 -lobjc
```

**Comment by tmccombs** [comment]
I am having a similar problem with neovim. Not even <cr> works. 

NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/build/config -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/src -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-h1uUxA/neovim-0.1.7ubuntu1+git201703011728+3177+23~ubuntu14.04.1/build/include
Compiled by root@lgw01-32

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by rbong** [comment]
I've been having trouble reproducing this issue with similar compilations. Can anyone run this command and post the contents of their clipboard?
```redir @+ | 20verbose exe 'normal \<cr' | redir END```

**Comment by tmccombs** [comment]
I tried that. There is no output stored in the clipboard (or in messages if I don't do the redirect)

The mapping for <cr> in gitv is:

```
n  <CR>        *@:<C-U>call <SNR>25_OpenGitvCommit("Gedit", 0)<CR>
```

**Comment by MattSPalmer** [comment]
OP here. I've observed a couple things in the last few weeks. 

* I had previously reproduced the issue on multiple machines, but only with one very large repository with ~40k commits
* As of this week, I can no longer reproduce the issue, and the plugin is working properly.

**Comment by aeruder** [comment]
This is largely related to #115 and #114 I believe.  Saw the same behavior and tracked it down to this.

**Comment by rbong** [comment]
If this is happening only with a large repository, that would be it. Please feel free to reopen this issue if it persists.

**Comment by tmccombs** [comment]
It was indeed a large repository.
