### ISSUE TITLE
'<,'>Gitv! doesn't work

### ISSUE THREAD

**Issue by gsi-emejias** [gregsexton/gitv#112]
I try to see the changes of a range of lines and I'm getting the following error.

Error detected while processing function <SNR>61_OpenGitv..<SNR>61_OpenFileMode..<SNR>61_LoadGitv..<SNR>61_ConstructAndExecuteCmd..<SNR>61_ConstructR
angeBuffer..<SNR>61_GetFinalOutputForHashes:                                                                                                         
line    2:                                                                                                                                           
E119: Not enough arguments for function: s:ReapplyReservedArgs                                                                                       
E15: Invalid expression: s:ReapplyReservedArgs(['', ''])

**Comment by ipwnponies** [comment]
I bisected master branch, seems this commit introduced the bug: b0460fb18025b4ae4c2d4d880e09065d5e5b0573

To work around this while waiting for fix, configure your vim plugin management to use the last working commit, b70ea59fc05a450bd4b93d0876aadfd73a0d4fdc.

**Comment by rbong** [comment]
Should be fixed on the latest master, please leave a comment if it's still happening.

**Comment by gsi-emejias** [comment]
It's fixed now, thanks

**Comment by hulucc** [comment]
Not work for me...
Any advice?
![image](https://user-images.githubusercontent.com/4343900/42918148-28ef3b0c-8b3f-11e8-82f2-2f26456de872.png)
