### ISSUE TITLE
How to return back from opened diff on right panel?

### ISSUE THREAD

**Issue by alex-shamshurin** [gregsexton/gitv#123]
Commits tree is on the left side, diff summary is on the right window. <c-r> opens a diff. Ok, but how to come back to the summary?

**Comment by AGhost-7** [comment]
I was actually wondering the same. I think its probably just a normal diff which if that's the case you can't go back.

The file listings in the commit summary are by the looks of it just folded diffs. You can use `zo` to open then and `zc` to close (see `:h folding`).

**Comment by alex-shamshurin** [comment]
It must be a way to come back from diffs

**Comment by alex-shamshurin** [comment]
Ping! We really need this feature

**Comment by cronacronis** [comment]
Use `CTLR+W` then `<-` (left button).

**Comment by alex-shamshurin** [comment]
In my case I found a way how to return back ctrl-w ctrl-o

**Comment by rbong** [comment]
gw switches between the windows by default. Sorry for the delay!
