### ISSUE TITLE
:Gitv from new tab - E605: Exception not caught: fugitive: not a git repository

### ISSUE THREAD

**Issue by mckellyln** [gregsexton/gitv#132]
Running :Gitv works great, but if I open a new empty tab with
:tabnew and then run :Gitv from there I get this -

Error detected while processing function <SNR>33_OpenGitv[4]..<SNR>33_SanitizeReservedArgs[16]..fugitive#buffer[1]..<SNR>60_buffer[6]..<SNR>6
0_throw:
line    2:
E605: Exception not caught: fugitive: not a git repository:

But a 
:!pwd 
shows I'm in the same dir as the previous tab and it is a git repo dir.

**Comment by mckellyln** [comment]
## Gitv debug output
### Basic information
```
Version: 1.3.1.22
Mon 18 Jun 2018 04:26:07 PM EDT
```
### Settings
```
--- Options ---
  background=dark     expandtab           history=20          scroll=20           smarttab            ttimeout            t_BE=^[[?2004h
  backspace=2         filetype=sh         laststatus=2        shiftwidth=4      nostartofline         ttimeoutlen=700     t_BD=^[[?2004l
  bufhidden=hide      formatoptions=cql   mouse=a           noshowmode            syntax=sh           ttyfast
  commentstring=#%s   helplang=en         pyxversion=2        showtabline=2       tabstop=4           ttymouse=xterm
  confirm             hidden              ruler               signcolumn=yes      timeoutlen=700      virtualedit=block
  clipboard=unnamed,unnamedplus,autoselect,exclude:cons\|linux
  completefunc=RtagsCompleteFunc
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
  indentexpr=GetShIndent()
  indentkeys=0{,0},!^F,o,O,e,0=then,0=do,0=else,0=elif,0=fi,0=esac,0=done,0=end,),0=;;,0=;&,0=fin,0=fil,0=fip,0=fir,0=fix
  iskeyword=@,48-57,_,192-255,@-@,<,>,*,%,$,!,~,#,^
  runtimepath=~/.vim,~/.vim/bundle/Vundle.vim,~/.vim/bundle/vim-ingo-library,~/.vim/bundle/vim-UnconditionalPaste,~/.vim/bundle/vim-clang,~/.
vim/bundle/vim-rooter,~/.vim/bundle/vim-rtags,~/.vim/bundle/QFEnter,~/.vim/bundle/vim-fswitch,~/.vim/bundle/vim-filebeagle,~/.vim/bundle/vim-
gitgutter,~/.vim/bundle/vim-fugitive,~/.vim/bundle/gitv,~/.vim/bundle/fzf.vim,~/.vim/bundle/ack.vim,~/.vim/bundle/vim-deus,~/.vim/bundle/vim-
localvimrc,~/.vim/bundle/vim-polyglot,~/.vim/bundle/vim-cpp-enhanced-highlight,~/.vim/bundle/lightline.vim,~/.vim/bundle/vim-lastplace,~/.vim
/bundle/asyncrun.vim,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim81,/usr/local/share/vim/vim81/pack/dist/opt/termdebug,/usr/local/s
hare/vim/vimfiles/after,~/.vim/after,~/.vim/bundle/Vundle.vim,~/.fzf,~/.vim/bundle/Vundle.vim/after,~/.vim/bundle/vim-ingo-library/after,~/.v
im/bundle/vim-UnconditionalPaste/after,~/.vim/bundle/vim-clang/after,~/.vim/bundle/vim-rooter/after,~/.vim/bundle/vim-rtags/after,~/.vim/bund
le/QFEnter/after,~/.vim/bundle/vim-fswitch/after,~/.vim/bundle/vim-filebeagle/after,~/.vim/bundle/vim-gitgutter/after,~/.vim/bundle/vim-fugit
ive/after,~/.vim/bundle/gitv/after,~/.vim/bundle/fzf.vim/after,~/.vim/bundle/ack.vim/after,~/.vim/bundle/vim-deus/after,~/.vim/bundle/vim-loc
alvimrc/after,~/.vim/bundle/vim-polyglot/after,~/.vim/bundle/vim-cpp-enhanced-highlight/after,~/.vim/bundle/lightline.vim/after,~/.vim/bundle
/vim-lastplace/after,~/.vim/bundle/asyncrun.vim/after
  statusline=%{lightline#link()}%#LightlineLeft_active_0#%( %{MyLightlineMode()} %)%{MyLightlineMode()!=#""&&((&paste))?"|":""}%( %{&paste?"P
ASTE":""} %)%#LightlineLeft_active_0_1#%#LightlineLeft_active_1#%( %{MyLightlineGitbranch()} %)%{MyLightlineGitbranch()!=#""&&(MyLightlineFil
ename()!=#""||MyLightlineModified()!=#"")?"|":""}%( %{MyLightlineFilename()} %)%{MyLightlineFilename()!=#""&&(MyLightlineModified()!=#"")?"|"
:""}%( %{MyLightlineModified()} %)%#LightlineLeft_active_1_2#%#LightlineMiddle_active#%=%#LightlineRight_active_2_3#%#LightlineRight_active_2
#%( %{&ff} %)%{1||1?"|":""}%( %{&fenc!=#""?&fenc:&enc} %)%{1?"|":""}%( %{&ft!=#""?&ft:"no ft"} %)%#LightlineRight_active_1_2#%#LightlineRight
_active_1#%( %3p%% %)%#LightlineRight_active_0_1#%#LightlineRight_active_0#%( %3l:%-2v %)
  tabline=%!lightline#tabline()
  viminfo='20,"20,f20
  t_EI=^[Ptmux;^[^[[?2004l^[\
  t_SI=^[Ptmux;^[^[[?2004h^[\
### Vim version
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 18 2018 15:28:21)
Included patches: 1-73
Compiled by kellma02@hal9008
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      -perl              +tag_binary        +vreplace
+autocmd           +cursorbind        +gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      +mouseshape        +postscript        -tag_any_white     +wildmenu
+balloon_eval      +dialog_con_gui    +iconv             +mouse_dec         +printer           -tcl               +windows
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +writebackup
+browse            +digraphs          +job               -mouse_jsbterm     +python/dyn        +terminal          +X11
++builtin_terms    +dnd               +jumplist          +mouse_netterm     +python3/dyn       +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      +xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       +xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            +xsmp_interact
+clientserver      +ex_extra          +libcall           +mouse_xterm       -ruby              +title             +xterm_clipboard
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        +toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +virtualedit
+comments          +float             -lua               +num64             +statusline        +visual
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -
I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1
 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/includ
e/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTI
FY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgi
o-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo
 -lnsl    -ldl
```
### Git output
```
$ git --version
git version 2.17.1
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ git remote --verbose
origin  https://github.com/mckellyln/dotfiles.git (fetch)
origin  https://github.com/mckellyln/dotfiles.git (push)
```
### Fugitive version
```
```

**Comment by mckellyln** [comment]
And when :call Gitv_GetDebugInfo() is run from new tab:
$ git --version
Gitv_GetDebugInfo exception:
fugitive: not a git repository:
```

But !pwd and !git status show I'm in the same dir and it is a git repo dir.

**Comment by AlterDepp** [comment]
Gitv/fugitive search a git repo for the file in the current buffer. A
new tab does not work, since there is no file. 

Am 2018-06-18 22:23, schrieb Mark Kelly:

> Running :Gitv works great, but if I open a new empty tab with
> :tabnew and then run :Gitv from there I get this - 
> 
> Error detected while processing function 33_OpenGitv[4]..33_SanitizeReservedArgs[16]..fugitive#buffer[1]..60_buffer[6]..6
> 0_throw:
> line 2:
> E605: Exception not caught: fugitive: not a git repository: 
> 
> But a
> :!pwd
> shows I'm in the same dir as the previous tab and it is a git repo dir. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/gregsexton/gitv/issues/132
[2]

**Comment by mckellyln** [comment]
Hi,
ok, thanks.  But if I open vim without a file it works ok.  Only a new tab causes this issue.

**Comment by mckellyln** [comment]
I suppose its more of a fugitive issue (if its a real issue at all) ?

**Comment by mckellyln** [comment]
This is not supported, see -
https://github.com/tpope/vim-fugitive/issues/1043
