### ISSUE TITLE
Exception not caught: fugitive: Removed in favor of fugitive#repo()

### ISSUE THREAD

**Issue by dkvasnicka** [gregsexton/gitv#135]
Fugitive recently underwent some major changes and after updating everything and trying to run Gitv I get:

```
Error detected while processing function <SNR>89_OpenGitv[4]..<SNR>89_SanitizeReservedArgs[16]..<SNR>224_buffer_repo:
line    1:
E605: Exception not caught: fugitive: Removed in favor of fugitive#repo()
Press ENTER or type command to continue
```

The same error also appears during `Gitv_GetDebugInfo()` when it tries to get the current git version.

**Comment by rbong** [comment]
Mostly we use `fugitive#buffer().repo()` so it's a simple search-and-replace, but we also use `fugitive#buffer().path()` once. If anyone has a solution please post it here.

**Comment by sankhesh** [comment]
Looking at https://github.com/tpope/vim-fugitive/commit/d41dee9c0b0cd2ffc364f2784d764b76e43ae057, it seems like just replace 'fugitive#buffer().path()' with 'FugitivePath'. What do you think?

**Comment by rbong** [comment]
That will work. We'll need to store the original buffer as well. Pull requests are accepted, I'm not sure when I can work on this.
