### ISSUE TITLE
<CR> in Gitv doesn't work

### ISSUE THREAD

**Issue by phmarek** [gregsexton/gitv#22]
When I open a file from a git repository, eg. Ge ^ works as expected.

But if I get a new buffer with Gitv, pressing `<CR>` on a line says

```
 E492: Not an editor command Gedit ad61e12
```

Please see https://github.com/tpope/vim-fugitive/issues/142 for more details.

**Comment by mpereira** [comment]
This still seems to happen with [dbext](https://github.com/vim-scripts/dbext.vim) versions 20.00 and 21.00.
