### ISSUE TITLE
Make it a true gitk replacement

### ISSUE THREAD

**Issue by sorin-ionescu** [gregsexton/gitv#5]
Thank you for creating gitv. It's a promising replacement for gitk and tig. However, make it a true replacement for gitk by adding a Git hook, if possible, to open gitv instead of gitk.

**Comment by blockloop** [comment]
This works if you're in a subdirectory of your git project (assuming you have [upsearch](https://gist.github.com/blockloop/353770cec31f5b82a8a7)) in your .bashrc

`alias gitv='vi "$(upsearch .git)/.git/index" -c "Gitv —all" -c "tabonly"'`

**Comment by aschrab** [comment]
@blockloop not all repositories will have the git directory as `.git` at the top level. Probably the most common reason for that being different is in repositories that are submodules of another repository. You can reliably get the path to the git directory of the current repository using `git rev-parse --git-dir`, this also avoids depending on non-standard commands.

    alias gitv='vim "$(git rev-parse --git-dir)/index" -c "Gitv --all" -c tabonly'

**Comment by blockloop** [comment]
ah yes, much better

**Comment by rbong** [comment]
Bisect is now available at #104
Take that, magit.
