### ISSUE TITLE
Error when using O map in browser mode

### ISSUE THREAD

**Issue by idbrii** [gregsexton/gitv#57]
I get this error when pressing `O` on a commit in browser mode:

```
Error detected while processing function <SNR>69_OpenGitvCommit..<SNR>69_MoveIntoPreviewAndExecute..<SNR>69_AttemptToCreateAPreviewWindow:
line    5:
No preview window detected.
```

Aside from that error, the commit is correctly opened in a new tab. I'm not sure why it's trying to use a preview window (or what would be in the preview window).

Using `CR` opens the commit in the right pane without error. So I guess something with the new tab handling is trying and failing to open a preview window.

**Comment by rbong** [comment]
I believed this was fixed when I removed a case where warnings were always thrown. Please re-open this if you continue to have issues.
