### ISSUE TITLE
filtering by file or directory fails

### ISSUE THREAD

**Issue by zsorizs** [gregsexton/gitv#68]
Issuing :Gitv somedir/ fails with this error:
fatal: bad flag '--no-color' used after filename

I quite frequently filter commits by specific directories or files and it would be nice to see the log with gitv.

**Comment by rbong** [comment]
I solved this by splitting up the arguments passed to gitv and re-applying the filenames where appropriate. This is heavily experimental but hopefully lays the foundation for more argument parsing and modification in the future. Please re-open this issue or start another issue if there are any problems.
