### ISSUE TITLE
Open PreviewWindow if is not open

### ISSUE THREAD

**Issue by wikimatze** [gregsexton/gitv#82]
Hi Greg, 

I really love your plugin. Sometimes I want to close the preview window to see more of history. When I then press on a commit to see the changed files I get the following error:

``` vim
".git/HEAD" 1 line --100%--
Error detected while processing function <SNR>79_OpenGitvCommit..<SNR>79_MoveIntoPreviewAndExecute..<SNR>79_AttemptToCreateAPreviewWindow..<SNR>79_MoveIntoPreviewAndExecute.
.<SNR>79_AttemptToCreateAPreviewWindow:
line    5:
No preview window detected.
Error detected while processing function <SNR>79_OpenGitvCommit..<SNR>79_MoveIntoPreviewAndExecute..<SNR>79_AttemptToCreateAPreviewWindow:
line    5:
No preview window detected.
```

Do you think this feature would make sense? If yes, I can try to implement it.

Best regards,

Matthias

**Comment by rbong** [comment]
This has been working for a while. Cleaning this issue up.

**Comment by wikimatze** [comment]
That's fine for me.
