### ISSUE TITLE
Improve file mode for git repositories with a large history

### ISSUE THREAD

**Issue by sunnyps** [gregsexton/gitv#86]
I tried file mode on the chromium source code and I can't find any recent commits for any range of lines I select. I suspect this is because the git history is so large that the default limit of 44 commits doesn't count for much. It would be great if gitv could do a reverse search kinda like what git blame does. I'm not sure if you're already doing this so feel free to close this bug if you are.

**Comment by rbong** [comment]
Does being able to use `--grep` and `-G` to search solve your problem? How else might one improve reverse searching?

**Comment by rbong** [comment]
I'm closing up this issue for now. Please try the arguments and feel free to re-open the issue or post a new issue if it's not sufficient.
