### ISSUE TITLE
[RFE] add support for opening a file in the working tree given a file in the history

### ISSUE THREAD

**Issue by mathstuf** [gregsexton/gitv#88]
It would be nice when browsing a diffstat or a file from the history to open the file as it currently exists (possibly with a diff of the current view against it). It seems that from the docs, `D` should do this, but I don't see it in the list of bindings from `:nor`.

**Comment by rbong** [comment]
You can open the current file or working version by pressing `<CR>` over the file, then while inside using `:Gedit<CR>`. This functionality comes from fugitive.
