### ISSUE TITLE
:Gitv! ctrl-enter not working

### ISSUE THREAD

**Issue by cj** [gregsexton/gitv#99]
It states here http://www.gregsexton.org/2011/05/gitv-range/ that you can use `ctrl-enter` to view the headers of a commit, this doesn't appear to be the case.  Doing `ctrl-enter` just opens up the commit again with no headers.  Am I missing something?

Thank you!

**Comment by rbong** [comment]
In many terminals, control-enter is bound to plain old enter. Sorry for the wait.
